kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      tier: backend
  template:
    metadata:
      labels:
        app: platform
        tier: backend
    spec:
      containers:
        - name : backend
          image : europe-west1-docker.pkg.dev/dsn-dev-01/backend-repository/backend_webapp:latest
          imagePullPolicy: Always
          ports:
            - name: port1
              containerPort: 5000

---

kind: Service
apiVersion: v1
metadata:
  name: backend-node-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http